import { AnalyzeState } from '../types';

export const IdentifiedProblems: AnalyzeState = {
  'example.py@@1': {
    id: '1',
    isDiscarded: false,
    isEndorsed: false,
    isViewed: false,
    path: 'example.py',
    startLine: 2,
    endLine: 2,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example.py@@2': {
    id: '2',
    isDiscarded: false,
    isEndorsed: false,
    isViewed: false,
    path: 'example.py',
    startLine: 2,
    endLine: 2,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example.py@@3': {
    id: '3',
    isDiscarded: false,
    isEndorsed: false,
    isViewed: false,
    path: 'example.py',
    startLine: 2,
    endLine: 2,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example.py@@4': {
    id: '4',
    isDiscarded: false,
    isEndorsed: false,
    isViewed: true,
    path: 'example.py',
    startLine: 2,
    endLine: 3,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example.py@@5': {
    id: '5',
    isDiscarded: true,
    isEndorsed: true,
    isViewed: true,
    path: 'example.py',
    startLine: 2,
    endLine: 3,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example.py@@6': {
    id: '6',
    isDiscarded: true,
    isEndorsed: true,
    isViewed: true,
    path: 'example.py',
    startLine: 0,
    endLine: 0,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example2',
  },
  '7': {
    id: '7',
    isDiscarded: true,
    isEndorsed: true,
    isViewed: true,
    path: 'example.py',
    startLine: 0,
    endLine: 0,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example2',
  },
  '8': {
    id: '8',
    isDiscarded: true,
    isEndorsed: true,
    isViewed: true,
    path: 'example.py',
    startLine: 0,
    endLine: 0,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: undefined,
  },
  'example2.py@@9': {
    id: '9',
    isDiscarded: false,
    isEndorsed: true,
    isViewed: true,
    path: 'example2.py',
    startLine: 0,
    endLine: 0,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example2.py@@10': {
    id: '9',
    isDiscarded: false,
    isEndorsed: true,
    isViewed: false,
    path: 'example2.py',
    startLine: 2,
    endLine: 2,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example3.py@@11': {
    id: '11',
    isDiscarded: false,
    isEndorsed: true,
    isViewed: true,
    path: 'example3.py',
    startLine: 2,
    endLine: 2,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
  'example3.py': {
    id: '11',
    isDiscarded: false,
    isEndorsed: true,
    isViewed: true,
    path: 'example3.py',
    startLine: 2,
    endLine: 2,
    category: 'Logic',
    summary: 'Logic Error',
    description: 'Logic Error',
    severity: 'HIGH',
    fullFilePath: 'example',
  },
};
